// Restores a-breve/s-comma/t-comma diacritics that the OCR replaced with a
// single plain space (a-circumflex and i-circumflex were preserved by the
// OCR, confirmed by spot-checking the source).
const fs = require('fs');
let t = fs.readFileSync('calendar-2026-ro-raw-ocr.txt', 'utf8');

// Protect the calendar's own "Har i" fast-free marker before anything else
// touches it: parallel EN text confirms the meaning ("Fast Free") but not
// the exact RO spelling, so it is left as printed rather than guessed.
t = t.split('Har i').join('HARIPLACEHOLDER');

const SPECIFIC = [
  ['Sfin i i Mc.', 'Sfinții Mc.'],
  ['Sfin ii Mc.', 'Sfinții Mc.'],
  ['Sfin it Mc.', 'Sfințit Mc.'],
  ['Sfin i i', 'Sfinții'],
  ['Sfin ii', 'Sfinții'],
  ['Sfin ilor', 'Sfinților'],
  ['Sfin it', 'Sfințit'],
  ['M rturisitorul', 'Mărturisitorul'],
  ['M rturisitoarea', 'Mărturisitoarea'],
  ['M rturisitori', 'Mărturisitori'],
  ['M rturisitor', 'Mărturisitor'],
  ['Sf ntul', 'Sfântul'],
  ['Sf nta', 'Sfânta'],
  ['P rin ii', 'Părinții'],
  ['P rin ilor', 'Părinților'],
  ['P rin i', 'Părinți'],
  ['P storul', 'Păstorul'],
  ['Preo i', 'Preoți'],
  ['preo i', 'preoți'],
  ['dup trup', 'după trup'],
  ['dup Botezul', 'după Botezul'],
  ['dup Pa ti', 'după Paști'],
  ['dup Rusalii', 'după Rusalii'],
  ['dup Na terea', 'după Nașterea'],
  ['dup Na tere', 'după Naștere'],
  ['dup Adormirea', 'după Adormirea'],
  ['împreun cu', 'împreună cu'],
  ['Botez torul', 'Botezătorul'],
  ['T ierea', 'Tăierea'],
  ['(Înainte-pr znuirea', '(Înainte-prăznuirea'],
  ['pr znuirea', 'prăznuirea'],
  ['Sâmb ta', 'Sâmbăta'],
  ['mor ilor', 'morților'],
  ['Mo ii', 'Moșii'],
  ['adormi i', 'adormiți'],
  ['moa telor', 'moaștelor'],
  ['împ r teasa', 'împărăteasa'],
  ['împ ra i', 'împărați'],
  ['împ rat', 'împărat'],
  ['Împ ra i', 'Împărați'],
  ['Rug ciunea', 'Rugăciunea'],
  ['rug ciunea', 'rugăciunea'],
  ['N sc toarei', 'Născătoarei'],
  ['n sc toarei', 'născătoarei'],
  ['N sc toare', 'Născătoare'],
  ['n sc toare', 'născătoare'],
  ['Lumin torul', 'Luminătorul'],
  ['lumin torul', 'luminătorul'],
  ['Lumin toarea', 'Luminătoarea'],
  ['lumin toarea', 'luminătoarea'],
  ['f c torul', 'făcătorul'],
  ['F c torul', 'Făcătorul'],
  ['f r de argin i', 'fără de arginți'],
  ['M ntuitorul', 'Mântuitorul'],
  ['Judec i', 'Judecăți'],
  ['Judec ii', 'Judecății'],
  ['Înfrico toarei', 'Înfricoșătoarei'],
  ['L satul secului', 'Lăsatul secului'],
  ['L satului sec', 'Lăsatului sec'],
  ['brânz ', 'brânză '],
  ['Na terea', 'Nașterea'],
  ['na terea', 'nașterea'],
  ['na tere', 'naștere'],
  ['Na terii', 'Nașterii'],
  ['În l area', 'Înălțarea'],
  ['în l area', 'înălțarea'],
  ['Intr rii', 'Intrării'],
  ['intr rii', 'intrării'],
  ['biseric a', 'Biserică a'],
  ['rii Rom ne ti', 'Țării Românești'],
  ['Rom ni', 'Români'],
  ['rom ni', 'români'],
  ['sl vitul', 'slăvitul'],
  ['m rturisirea', 'mărturisirea'],
  ['s vâr i', 'săvârși'],
  ['s vâr esc', 'săvârșesc'],
  ['sl b nogului', 'slăbănogului'],
  ['Z vorâtul', 'Zăvorâtul'],
  ['Z mislirea', 'Zămislirea'],
  ['împ ratului', 'împăratului'],
  ['T m duirea', 'Tămăduirea'],
  ['t m duirea', 'tămăduirea'],
  ['T m duitor', 'Tămăduitor'],
  ['purt torul de biruin ', 'purtătorul de biruință'],
  ['Gr dinarul', 'Grădinarul'],
  ['gr dinarul', 'grădinarul'],
  ['buc tarul', 'bucătarul'],
  ['Sih stria', 'Sihăstria'],
  ['M n stirea', 'Mănăstirea'],
  ['m n stirea', 'mănăstirea'],
  ['Stâni oara', 'Stânișoara'],
  ['V ratec', 'Văratec'],
  ['Cet ii Albe', 'Cetății Albe'],
  ['În elepciunea', 'Înțelepciunea'],
  ['Credin a', 'Credința'],
  ['N dejdea', 'Nădejdea'],
  ['Ar tarea', 'Arătarea'],
  ['Ar tare', 'Arătare'],
  ['Vame ului', 'Vameșului'],
  ['lan ului', 'lanțului'],
  ['episcopul Cet ii', 'episcopul Cetății'],
  ['m rt.', 'mărt.'],
  ['Str mo i', 'Strămoși'],
  ['Dreg torul', 'Dregătorul'],
  ['P zirea', 'Păzirea'],
  ['lucr torilor r i', 'lucrătorilor răi'],
  ['de la Calapode ti', 'de la Calapodești'],
  ['propov duirii', 'propovăduirii'],
  ['încep torul vie ii c lug re ti de ob te', 'începătorul vieții călugărești de obște'],
  ['diaconi a', 'diaconița'],
  ['Coliba ul', 'Colibașul'],
  ['Danact citeul', 'Danact citețul'],
  ['lepro i', 'leproși'],
  ['Gur de Aur', 'Gură de Aur'],
  ['doctori f r de argin ', 'doctori fără de arginți '],
  ['dela Iordan', 'de la Iordan'],
  ['Filit i Lidia', 'Filet și Lidia'],
  ['Iona i Varahisie', 'Iona și Varahisie'],
  ['so ia sa', 'soția sa'],
  ['În l rii', 'Înălțării'],
  ['în l rii', 'înălțării'],
  ['Schimb rii la Fa a Domnului', 'Schimbării la Față a Domnului'],
  ['Tân rul bogat', 'Tânărul bogat'],
  ['Râ ca și Secu', 'Râșca și Secu'],
  ['Pâng ra i', 'Pângărați'],
  ['Tazl u', 'Tazlău'],
  ['Arge ;', 'Argeș;'],
  ['Arge .', 'Argeș.'],
  ['de la Arge ', 'de la Argeș '],
  ['S murc e ti', 'Șamurcășești'],
  ['aliturgic .', 'aliturgică.'],
  ['Ioan Sc rarul', 'Ioan Scărarul'],
  ['s racul', 'săracul'],
  ['v duvei', 'văduvei'],
  ['sem n torului', 'semănătorului'],
  ['p timit', 'pătimit'],
  ['Simion tefan', 'Simion Ștefan'],
  ['Voievod tefan cel Mare', 'Voievod Ștefan cel Mare'],
  ['Sf. Cuv. tefan', 'Sf. Cuv. Ștefan'],
  ['Înjum t irea', 'Înjumătățirea'],
  ['Înjum t irii', 'Înjumătățirii'],
  ['fii ai s i', 'fiii ai săi'],
  ['patru fii ai s i', 'patru fii ai săi'],
  ['nepoata sa', 'nepoata sa'],
  ['C ld ru ani', 'Căldărușani'],
  ['episcopul Prusiei', 'episcopul Prusiei'],
  ['Slujba lui se va s vâr i', 'Slujba lui se va săvârși'],
  ['se va s vâr i', 'se va săvârși'],
  ['s vâr te te', 'săvârșește'],
  ['dela Cernica', 'de la Cernica'],
  ['dela Neam ', 'de la Neamț'],
  ['de la Neam ;', 'de la Neamț;'],
  ['de la Neam ', 'de la Neamț '],
  ['Sih stria Putnei', 'Sihăstria Putnei'],
  ['episcopul Sinadei', 'episcopul Sinadei'],
  ['aducerea la Bari', 'aducerea la Bari'],
  ['Râ ca i Secu', 'Râșca și Secu'],
  ['Eusta ie', 'Eustatie'],
  ['Suta ul', 'Sutașul'],
  ['întâia Muceni și întocmai', 'întâia Muceniță și întocmai'],
  ['vr jma ilor', 'vrăjmașilor'],
  ['cere tilor', 'cereștilor'],
  ['încep torul vie ii c lug re ti de\nob te', 'începătorul vieții călugărești de obște'],
  ['Cuvio i)', 'Cuvioși)'],
  ['St niloae', 'Stăniloae'],
  ['de iarn )', 'de iarnă)'],
  ['de var )', 'de vară)'],
  ['de toamn )', 'de toamnă)'],
  ['T m duirii', 'Tămăduirii'],
  ['Rom ne ti', 'Românești'],
  ['Laz r', 'Lazăr'],
  ['Ia i;', 'Iași;'],
  ['Ia i,', 'Iași,'],
  ['la Ia i', 'la Iași'],
  ['Întâmpin rii', 'Întâmpinării'],
];

for (const [pat, rep] of SPECIFIC) {
  t = t.split(pat).join(rep);
}

t = t.split(' i i ').join(' ii ');
t = t.split('Pa ti').join('Paști');

// Final generic pass: standalone " i " -> " si " (represents "si"/"and").
t = t.replace(/(^|[\s(;,])i(?=[\s).,;]|$)/gm, '$1și');

// Restore the protected idiom. Cross-referencing the correctly-typed
// "Rânduieli Bisericești" regulations section at the end of this same
// source (not OCR-derived, pasted with correct diacritics already) confirms
// this calendar's own term for its fast-free marker is "harți" ("Miercurile
// și vinerile ... însemnate cu harți") — so this is a confident restoration,
// not a guess.
t = t.split('HARIPLACEHOLDER').join('harți');

// Normalize legacy cedilla diacritics (ş/ţ) to the modern comma-below forms
// (ș/ț) used everywhere else in this file, for consistency.
t = t.replace(/ş/g, 'ș').replace(/Ş/g, 'Ș').replace(/ţ/g, 'ț').replace(/Ţ/g, 'Ț');

fs.writeFileSync('calendar-2026-ro-pass1.txt', t);
console.log('done, wrote calendar-2026-ro-pass1.txt');
